import express from 'express';
import cors from 'cors';
import crypto from 'crypto';
import { v4 as uuid } from 'uuid';
import { existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { readDb, writeDb } from './db.js';
import { generateRoundRobin, generateRoundRobinDouble } from './services/roundRobin.js';
import { buildBracketRounds, buildDoubleElimBracket, RESERVED_SLOT } from './services/bracket.js';
import { computeStandings } from './services/standings.js';
import { computeTeamStandings } from './services/teamStandings.js';
import { computeTourStandings } from './services/tours.js';
import { buildPlayerProfile } from './services/playerProfile.js';
import { ApiError } from './errors.js';
import {
  CLASSIFICATIONS,
  hashPassword,
  verifyPassword,
  generateTempPassword,
  createSessionToken,
  verifySessionToken,
  publicUser,
  requireAuth,
  requireAdmin,
  requireAnyAdmin,
  assertLeagueAccess,
  generateApiKeyValue,
  hashApiKey,
} from './userAuth.js';
import { recordAudit } from './services/auditLog.js';

const STATUSES = ['active', 'suspended'];

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CLIENT_DIST = path.join(__dirname, '..', '..', 'client', 'dist');

const app = express();
app.use(cors());
app.use(express.json({ limit: '5mb' })); // season CSV/Excel imports can be a few hundred rows

const asyncRoute = (fn) => (req, res, next) => {
  try {
    fn(req, res);
  } catch (err) {
    next(err);
  }
};

const SCHEDULING_TYPES = ['round_robin_single', 'round_robin_double', 'knockout_single_elim', 'knockout_double_elim'];

// ---------- Accounts & auth ----------
// One account model, one login. `db.users` holds everyone; `isAdmin` and
// `isCaptain` are just boolean flags on an account rather than a separate
// kind of account. Anyone can self-register (POST /users/register), and an
// admin can flag any account as admin and/or captain from the user
// management screen, or via the season CSV/Excel import.

app.post('/api/auth/login', asyncRoute((req, res) => {
  const { email, password } = req.body;
  if (!email || !password) throw new ApiError(400, 'Email and password are required');

  const db = readDb();
  const normalizedEmail = email.trim().toLowerCase();
  const user = db.users.find((u) => u.email.toLowerCase() === normalizedEmail);
  if (!user || !verifyPassword(password, user.passwordHash)) {
    throw new ApiError(401, 'Invalid email or password');
  }
  if (user.status === 'suspended') {
    throw new ApiError(403, 'This account has been suspended');
  }

  const { token, expiresAt } = createSessionToken(user.id);
  res.json({ token, expiresAt, user: publicUser(user) });
}));

// Consumes a password-reset link generated by an admin from a player's
// profile page (see POST /api/admin/users/:id/send-reset-link below) -
// public/unauthenticated, since the whole point is for someone who's lost
// access to their password to be able to set a new one. The token itself is
// the credential here (a long random value, single-use, short-lived), so
// there's nothing else to check the requester's identity against.
app.post('/api/auth/reset-password/:token', asyncRoute((req, res) => {
  const { newPassword } = req.body;
  if (!newPassword || newPassword.length < 8) throw new ApiError(400, 'New password must be at least 8 characters');

  const db = readDb();
  const reset = db.passwordResets.find((r) => r.token === req.params.token);
  if (!reset) throw new ApiError(404, 'This reset link is invalid');
  if (reset.usedAt) throw new ApiError(400, 'This reset link has already been used - ask an admin to send a new one');
  if (Date.now() > reset.expiresAt) throw new ApiError(400, 'This reset link has expired - ask an admin to send a new one');

  const user = db.users.find((u) => u.id === reset.userId);
  if (!user) throw new ApiError(404, 'Account not found');

  user.passwordHash = hashPassword(newPassword);
  reset.usedAt = new Date().toISOString();
  writeDb(db);
  res.json({ ok: true });
}));

app.post('/api/users/register', asyncRoute((req, res) => {
  const {
    firstName, lastName, email, password,
    phone = '', teamName = '', classification = null,
  } = req.body;

  if (!firstName || !firstName.trim()) throw new ApiError(400, 'First name is required');
  if (!lastName || !lastName.trim()) throw new ApiError(400, 'Last name is required');
  if (!email || !email.trim()) throw new ApiError(400, 'Email is required');
  if (!password || password.length < 8) throw new ApiError(400, 'Password must be at least 8 characters');
  if (classification && !CLASSIFICATIONS.includes(classification)) {
    throw new ApiError(400, `classification must be one of: ${CLASSIFICATIONS.join(', ')}`);
  }

  const db = readDb();
  const normalizedEmail = email.trim().toLowerCase();
  if (db.users.some((u) => u.email.toLowerCase() === normalizedEmail)) {
    throw new ApiError(409, 'An account with this email already exists');
  }

  const user = createUserAccount(db, {
    firstName: firstName.trim(),
    lastName: lastName.trim(),
    email: email.trim(),
    passwordHash: hashPassword(password),
    phone: phone ? phone.trim() : '',
    // Team name is optional at self-registration (unlike the admin bulk-add
    // and season-import flows, which default a blank one to 'Unassigned') -
    // a player can register before knowing/being assigned to a team, so an
    // empty string is left as-is here rather than substituted.
    teamName: teamName ? teamName.trim() : '',
    classification: classification || null,
    isAdmin: false,
    isCaptain: false,
  });
  writeDb(db);

  const { token, expiresAt } = createSessionToken(user.id);
  res.status(201).json({ token, expiresAt, user: publicUser(user) });
}));

app.get('/api/users/me', requireAuth, asyncRoute((req, res) => {
  res.json(publicUser(req.auth.user));
}));
