import express from 'express';
import cors from 'cors';
import crypto from 'crypto';
import { v4 as uuid } from 'uuid';
import { existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { readDb, writeDb } from './db.js';
import { generateRoundRobin } from './services/roundRobin.js';
import { buildBracketRounds, buildDoubleElimBracket } from './services/bracket.js';
import { computeStandings } from './services/standings.js';
import { computeTeamStandings } from './services/teamStandings.js';
import { buildPlayerProfile } from './services/playerProfile.js';
import { ApiError } from './errors.js';
import {
  CLASSIFICATIONS,
  hashPassword,
  verifyPassword,
  generateTempPassword,
  createSessionToken,
  verifySessionToken,
  publicUser,
  requireAuth,
  requireAdmin,
} from './userAuth.js';
import { recordAudit } from './services/auditLog.js';

const STATUSES = ['active', 'suspended'];

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CLIENT_DIST = path.join(__dirname, '..', '..', 'client', 'dist');

const app = express();
app.use(cors());
app.use(express.json({ limit: '5mb' })); // season CSV/Excel imports can be a few hundred rows

const asyncRoute = (fn) => (req, res, next) => {
  try {
    fn(req, res);
  } catch (err) {
    next(err);
  }
};

const SCHEDULING_TYPES = ['round_robin_single', 'knockout_single_elim', 'knockout_double_elim'];

// ---------- Accounts & auth ----------
// One account model, one login. `db.users` holds everyone; `isAdmin` and
// `isCaptain` are just boolean flags on an account rather than a separate
// kind of account. Anyone can self-register (POST /users/register), and an
// admin can flag any account as admin and/or captain from the user
// management screen, or via the season CSV/Excel import.

app.post('/api/auth/login', asyncRoute((req, res) => {
  const { email, password } = req.body;
  if (!email || !password) throw new ApiError(400, 'Email and password are required');

  const db = readDb();
  const normalizedEmail = email.trim().toLowerCase();
  const user = db.users.find((u) => u.email.toLowerCase() === normalizedEmail);
  if (!user || !verifyPassword(password, user.passwordHash)) {
    throw new ApiError(401, 'Invalid email or password');
  }
  if (user.status === 'suspended') {
    throw new ApiError(403, 'This account has been suspended');
  }

  const { token, expiresAt } = createSessionToken(user.id);
  res.json({ token, expiresAt, user: publicUser(user) });
}));

// Consumes a password-reset link generated by an admin from a player's
// profile page (see POST /api/admin/users/:id/send-reset-link below) -
// public/unauthenticated, since the whole point is for someone who's lost
// access to their password to be able to set a new one. The token itself is
// the credential here (a long random value, single-use, short-lived), so
// there's nothing else to check the requester's identity against.
app.post('/api/auth/reset-password/:token', asyncRoute((req, res) => {
  const { newPassword } = req.body;
  if (!newPassword || newPassword.length < 8) throw new ApiError(400, 'New password must be at least 8 characters');

  const db = readDb();
  const reset = db.passwordResets.find((r) => r.token === req.params.token);
  if (!reset) throw new ApiError(404, 'This reset link is invalid');
  if (reset.usedAt) throw new ApiError(400, 'This reset link has already been used - ask an admin to send a new one');
  if (Date.now() > reset.expiresAt) throw new ApiError(400, 'This reset link has expired - ask an admin to send a new one');

  const user = db.users.find((u) => u.id === reset.userId);
  if (!user) throw new ApiError(404, 'Account not found');

  user.passwordHash = hashPassword(newPassword);
  reset.usedAt = new Date().toISOString();
  writeDb(db);
  res.json({ ok: true });
}));

app.post('/api/users/register', asyncRoute((req, res) => {
  const {
    firstName, lastName, email, password,
    phone = '', teamName, classification = null,
  } = req.body;

  if (!firstName || !firstName.trim()) throw new ApiError(400, 'First name is required');
  if (!lastName || !lastName.trim()) throw new ApiError(400, 'Last name is required');
  if (!email || !email.trim()) throw new ApiError(400, 'Email is required');
  if (!password || password.length < 8) throw new ApiError(400, 'Password must be at least 8 characters');
  if (!teamName || !teamName.trim()) throw new ApiError(400, 'Team name is required');
  if (classification && !CLASSIFICATIONS.includes(classification)) {
    throw new ApiError(400, `classification must be one of: ${CLASSIFICATIONS.join(', ')}`);
  }

  const db = readDb();
  const normalizedEmail = email.trim().toLowerCase();
  if (db.users.some((u) => u.email.toLowerCase() === normalizedEmail)) {
    throw new ApiError(409, 'An account with this email already exists');
  }

  const user = createUserAccount(db, {
    firstName: firstName.trim(),
    lastName: lastName.trim(),
    email: email.trim(),
    passwordHash: hashPassword(password),
    phone: phone ? phone.trim() : '',
    teamName: teamName.trim(),
    classification: classification || null,
    isAdmin: false,
    isCaptain: false,
  });
  writeDb(db);

  const { token, expiresAt } = createSessionToken(user.id);
  res.status(201).json({ token, expiresAt, user: publicUser(user) });
}));

app.get('/api/users/me', requireAuth, asyncRoute((req, res) => {
  res.json(publicUser(req.auth.user));
}));

// A player's league/division membership, shown as a static read-only field
// in the Player Portal's "Your Details" section - deliberately separate from
// GET /api/users/me/fixtures (which only reflects divisions that already
// have released fixtures), so a newly-registered player who hasn't been
// fixtured yet still sees which league/division they're in.
app.get('/api/users/me/leagues', requireAuth, asyncRoute((req, res) => {
  const db = readDb();
  const playerId = req.auth.user.playerId;
  if (!playerId) return res.json([]);
  const myTeamIds = db.teams.filter((t) => t.playerIds.includes(playerId)).map((t) => t.id);
  const myPairingIds = db.pairings.filter((p) => p.playerIds.includes(playerId)).map((p) => p.id);
  const divisions = db.divisions.filter((d) =>
    (d.playerIds || []).includes(playerId) ||
    (d.teamIds || []).some((id) => myTeamIds.includes(id)) ||
    (d.pairingIds || []).some((id) => myPairingIds.includes(id))
  );
  const result = divisions.map((d) => {
    const league = db.leagues.find((l) => l.id === d.leagueId);
    return { leagueName: league?.name || 'Unknown league', divisionName: d.name };
  });
  res.json(result);
}));

// Shared account-creation helper: builds the User record (and its linked
// Player roster entry, find-or-create by name) the same way whether the
// account came from self-registration, the season CSV/Excel import, or the
// wizard's "add a player manually" step. Doesn't write to disk - caller
// batches the writeDb() once all rows in a request are processed.
function createUserAccount(db, fields) {
  const fullName = `${fields.firstName} ${fields.lastName}`;
  let linkedPlayer = db.players.find((p) => p.name.toLowerCase() === fullName.toLowerCase());
  if (!linkedPlayer) {
    linkedPlayer = { id: uuid(), name: fullName };
    db.players.push(linkedPlayer);
  }
  const user = {
    id: uuid(),
    firstName: fields.firstName,
    lastName: fields.lastName,
    email: fields.email,
    passwordHash: fields.passwordHash,
    phone: fields.phone || '',
    teamName: fields.teamName,
    classification: fields.classification || null,
    isAdmin: !!fields.isAdmin,
    isCaptain: !!fields.isCaptain,
    status: 'active',
    playerId: linkedPlayer.id,
    createdAt: new Date().toISOString(),
  };
  db.users.push(user);
  return user;
}

// Keeps a User's linked Player roster entry's display name in sync whenever
// the account's name changes, whether the edit came from the player
// themselves or from an admin.
function syncLinkedPlayerName(db, user) {
  if (!user.playerId) return;
  const player = db.players.find((p) => p.id === user.playerId);
  if (player) player.name = `${user.firstName} ${user.lastName}`;
}

function applyProfileFields(db, user, fields) {
  const { firstName, lastName, email, phone, teamName, classification } = fields;
  if (firstName !== undefined) {
    if (!firstName || !firstName.trim()) throw new ApiError(400, 'First name is required');
    user.firstName = firstName.trim();
  }
  if (lastName !== undefined) {
    if (!lastName || !lastName.trim()) throw new ApiError(400, 'Last name is required');
    user.lastName = lastName.trim();
  }
  if (email !== undefined) {
    if (!email || !email.trim()) throw new ApiError(400, 'Email is required');
    const normalized = email.trim().toLowerCase();
    if (db.users.some((u) => u.id !== user.id && u.email.toLowerCase() === normalized)) {
      throw new ApiError(409, 'An account with this email already exists');
    }
    user.email = email.trim();
  }
  if (phone !== undefined) user.phone = phone ? phone.trim() : '';
  if (teamName !== undefined) {
    if (!teamName || !teamName.trim()) throw new ApiError(400, 'Team name is required');
    user.teamName = teamName.trim();
  }
  if (classification !== undefined) {
    if (classification && !CLASSIFICATIONS.includes(classification)) {
      throw new ApiError(400, `classification must be one of: ${CLASSIFICATIONS.join(', ')}`);
    }
    user.classification = classification || null;
  }
  syncLinkedPlayerName(db, user);
}

app.patch('/api/users/me', requireAuth, asyncRoute((req, res) => {
  const db = readDb();
  const user = db.users.find((u) => u.id === req.auth.userId);
  applyProfileFields(db, user, req.body);
  writeDb(db);
  res.json(publicUser(user));
}));

app.post('/api/users/me/change-password', requireAuth, asyncRoute((req, res) => {
  const { currentPassword, newPassword } = req.body;
  if (!currentPassword || !newPassword) {
    throw new ApiError(400, 'Current and new password are required');
  }
  if (newPassword.length < 8) throw new ApiError(400, 'New password must be at least 8 characters');

  const db = readDb();
  const user = db.users.find((u) => u.id === req.auth.userId);
  if (!verifyPassword(currentPassword, user.passwordHash)) {
    throw new ApiError(401, 'Current password is incorrect');
  }
  user.passwordHash = hashPassword(newPassword);
  writeDb(db);
  res.json({ ok: true });
}));

// A player's own upcoming/recent fixtures, across every division they're
// registered in (singles) or rostered onto (teams) - powers the Player
// Portal's "My Fixtures" panel without the client having to know which
// divisions/teams they belong to.
app.get('/api/users/me/fixtures', requireAuth, asyncRoute((req, res) => {
  const db = readDb();
  const user = req.auth.user;
  if (!user.playerId) return res.json([]);
  const playerId = user.playerId;

  const myTeamIds = db.teams.filter((t) => t.playerIds.includes(playerId)).map((t) => t.id);
  const myPairingIds = db.pairings.filter((p) => p.playerIds.includes(playerId)).map((p) => p.id);

  const fixtures = db.fixtures.filter((f) => {
    if (f.homePlayerId === playerId || f.awayPlayerId === playerId) return true;
    if (myTeamIds.includes(f.homeTeamId) || myTeamIds.includes(f.awayTeamId)) return true;
    if (myPairingIds.includes(f.homePlayerId) || myPairingIds.includes(f.awayPlayerId)) return true;
    return false;
  });

  // Even a fixture you're actually in doesn't show up here until the admin
  // has released its round - see isRoundVisible above. An admin viewing their
  // own "My Fixtures" (if their account is also linked to a player) still
  // sees everything, same as everywhere else this gate applies.
  const visibleFixtures = user.isAdmin
    ? fixtures
    : fixtures.filter((f) => isRoundVisible(db.divisions.find((d) => d.id === f.divisionId), f.round));

  const enriched = visibleFixtures.map((f) => {
    const division = db.divisions.find((d) => d.id === f.divisionId);
    const league = db.leagues.find((l) => l.id === f.leagueId);
    const isTeams = !!f.legs;
    const isDoubles = division?.entryType === 'doubles';
    const opponentId = isTeams
      ? (myTeamIds.includes(f.homeTeamId) ? f.awayTeamId : f.homeTeamId)
      : isDoubles
        ? (myPairingIds.includes(f.homePlayerId) ? f.awayPlayerId : f.homePlayerId)
        : (f.homePlayerId === playerId ? f.awayPlayerId : f.homePlayerId);
    const opponentName = isTeams
      ? db.teams.find((t) => t.id === opponentId)?.name
      : isDoubles
        ? db.pairings.find((p) => p.id === opponentId)?.name
        : db.players.find((p) => p.id === opponentId)?.name;
    return {
      id: f.id,
      leagueName: league?.name,
      divisionName: division?.name,
      round: f.round,
      status: f.status,
      scheduledDate: f.scheduledDate || null,
      opponentName: opponentName || 'TBD',
    };
  });

  enriched.sort((a, b) => (a.scheduledDate || '').localeCompare(b.scheduledDate || '') || a.round - b.round);
  res.json(enriched);
}));

// A player's own results currently awaiting THEIR confirmation - fixtures
// where they're the home or away entrant (or team-fixture legs where they're
// the home- or away-nominated player) sitting at `pending_confirmation`,
// where THEIR side hasn't confirmed yet (see homeConfirmed/awayConfirmed -
// both sides must independently confirm before a result counts, see the
// "Result confirmation" section further down). This is the player-facing
// counterpart to the admin's Game Adjustments "Needs Attention" list
// (GET /api/admin/fixtures/needs-attention above), scoped to just the
// actions this one account can actually take - powers the "My Submissions"
// panel on the Player Portal (My Account). Defined here, ahead of
// isAwayEntrant/isHomeEntrant's declaration further down - safe because
// Express only calls this handler once a request arrives, long after every
// function declaration in the module has been hoisted and is available.
app.get('/api/users/me/pending-confirmations', requireAuth, asyncRoute((req, res) => {
  const db = readDb();
  const playerId = req.auth.user.playerId;
  const results = [];
  if (!playerId) return res.json(results);

  for (const f of db.fixtures) {
    const division = db.divisions.find((d) => d.id === f.divisionId);
    const league = db.leagues.find((l) => l.id === f.leagueId);
    // Same round-visibility gate as everywhere else - a result awaiting your
    // confirmation on a not-yet-released round shouldn't surface here either
    // (shouldn't normally happen since scoring itself is also blocked, but an
    // admin could in principle score ahead of release, so this stays
    // consistent rather than relying on that never happening).
    if (!req.auth.user.isAdmin && !isRoundVisible(division, f.round)) continue;

    if (f.legs) {
      const homeTeam = db.teams.find((t) => t.id === f.homeTeamId);
      const awayTeam = db.teams.find((t) => t.id === f.awayTeamId);
      for (const leg of f.legs) {
        if (leg.status !== 'pending_confirmation') continue;
        const isHome = leg.homePlayerId === playerId;
        const isAway = leg.awayPlayerId === playerId;
        if (!isHome && !isAway) continue;
        if (isHome && leg.homeConfirmed) continue;
        if (isAway && leg.awayConfirmed) continue;
        const opponentPlayer = db.players.find((p) => p.id === (isHome ? leg.awayPlayerId : leg.homePlayerId));
        results.push({
          fixtureId: f.id,
          legNumber: leg.legNumber,
          leagueName: league?.name,
          divisionName: division?.name,
          round: f.round,
          opponentName: opponentPlayer?.name || (isHome ? awayTeam?.name : homeTeam?.name) || 'TBD',
          scoreLabel: `${leg.homeFrameScore}-${leg.awayFrameScore} frames`,
        });
      }
      continue;
    }

    if (f.status !== 'pending_confirmation') continue;
    const isDoubles = division?.entryType === 'doubles';
    const isHome = isHomeEntrant(db, division, f, playerId);
    const isAway = isAwayEntrant(db, division, f, playerId);
    if (!isHome && !isAway) continue;
    if (isHome && f.homeConfirmed) continue;
    if (isAway && f.awayConfirmed) continue;
    const opponentId = isHome ? f.awayPlayerId : f.homePlayerId;
    const opponentName = isDoubles
      ? db.pairings.find((p) => p.id === opponentId)?.name
      : db.players.find((p) => p.id === opponentId)?.name;
    results.push({
      fixtureId: f.id,
      legNumber: null,
      leagueName: league?.name,
      divisionName: division?.name,
      round: f.round,
      opponentName: opponentName || 'TBD',
      scoreLabel: `${f.homeFrameScore}-${f.awayFrameScore} frames`,
      submittedAt: f.resultSubmittedAt || null,
    });
  }

  results.sort((a, b) => (a.leagueName || '').localeCompare(b.leagueName || '') || a.round - b.round);
  res.json(results);
}));

// ---------- Leagues ----------

app.get('/api/leagues', requireAuth, asyncRoute((req, res) => {
  const db = readDb();
  res.json(db.leagues);
}));

app.post('/api/leagues', requireAdmin, asyncRoute((req, res) => {
  const { name, sport = 'English 8-Ball Pool', matchFormat = 'singles', raceTo = 6, scheduling = 'round_robin_single' } = req.body;
  if (!name || !name.trim()) throw new ApiError(400, 'League name is required');

  const db = readDb();
  const league = {
    id: uuid(),
    name: name.trim(),
    sport,
    format: { matchFormat, raceTo, scheduling },
    startDate: null,
    endDate: null,
    createdAt: new Date().toISOString(),
  };
  db.leagues.push(league);
  writeDb(db);
  res.status(201).json(league);
}));

app.get('/api/leagues/:id', requireAuth, asyncRoute((req, res) => {
  const db = readDb();
  const league = db.leagues.find((l) => l.id === req.params.id);
  if (!league) throw new ApiError(404, 'League not found');
  const divisions = db.divisions
    .filter((d) => d.leagueId === league.id)
    .sort((a, b) => a.order - b.order);
  res.json({ ...league, divisions });
}));

// ---------- Divisions ----------
// A division has two independent axes:
// - entryType: "singles" (players register directly), "teams" (teams
//   register, each fixture is `legsPerMatch` nominated player-vs-player legs),
//   or "doubles" (2-3 named registered players register together as one
//   `Pairing` and play alternate-shot as a single side - structurally a
//   Pairing is just a named group of players like a Team, but a doubles/
//   triples fixture is scored exactly like a singles fixture: one continuous
//   frame race, no legs, `homePlayerId`/`awayPlayerId` just hold a Pairing id
//   instead of a Player id - see the "Pairings" section below)
// - scheduling: "round_robin_single" (default - everyone plays everyone once),
//   "knockout_single_elim" (single-elimination bracket, byes if the entrant
//   count isn't a power of 2), or "knockout_double_elim" (winners bracket +
//   losers bracket + Grand Final, with a bracket-reset decider if the
//   losers-bracket finalist wins the Grand Final - requires an exact
//   power-of-2 entrant count, see services/bracket.js). This can differ per
//   division from the league's own default, since a league often runs its
//   regular season as a round robin but a separate cup division as a
//   knockout.

app.post('/api/leagues/:leagueId/divisions', requireAdmin, asyncRoute((req, res) => {
  const { name, order = 0, entryType = 'singles', legsPerMatch = 5, pairingSize = 2 } = req.body;
  const db = readDb();
  const league = db.leagues.find((l) => l.id === req.params.leagueId);
  if (!league) throw new ApiError(404, 'League not found');
  const scheduling = req.body.scheduling || league.format.scheduling || 'round_robin_single';

  if (!name || !name.trim()) throw new ApiError(400, 'Division name is required');
  if (!['singles', 'teams', 'doubles'].includes(entryType)) {
    throw new ApiError(400, 'entryType must be "singles", "teams" or "doubles"');
  }
  if (!SCHEDULING_TYPES.includes(scheduling)) {
    throw new ApiError(400, `scheduling must be one of: ${SCHEDULING_TYPES.join(', ')}`);
  }
  if (entryType === 'teams' && (!Number.isInteger(Number(legsPerMatch)) || Number(legsPerMatch) < 1)) {
    throw new ApiError(400, 'legsPerMatch must be a positive whole number');
  }
  if (entryType === 'doubles' && ![2, 3].includes(Number(pairingSize))) {
    throw new ApiError(400, 'pairingSize must be 2 (doubles) or 3 (triples)');
  }

  const division = {
    id: uuid(),
    leagueId: league.id,
    name: name.trim(),
    order,
    entryType,
    scheduling,
    playerIds: [],
    teamIds: [],
    pairingIds: [],
    legsPerMatch: entryType === 'teams' ? Number(legsPerMatch) : null,
    pairingSize: entryType === 'doubles' ? Number(pairingSize) : null,
    gapDays: null,
    fixturesGenerated: false,
    // No round is visible to players until an admin explicitly releases it
    // from "Manage Fixtures" - see isRoundVisible / POST
    // /api/divisions/:id/rounds/:round/visibility below. Admins always see
    // every round regardless of this list.
    visibleRounds: [],
  };
  db.divisions.push(division);
  writeDb(db);
  res.status(201).json(division);
}));

// Round visibility ("Manage Fixtures"): a division's `visibleRounds` (array
// of round numbers) controls which rounds a non-admin account is allowed to
// see or take any action on at all - fixture lists, "My Fixtures"/"Needs Your
// Confirmation", direct fixture pages, and every scoring route. Admins always
// see and can act on every round regardless of this list, so a season can be
// built (and even scored ahead of time) before any of it is revealed to
// players. See POST /api/divisions/:id/rounds/:round/visibility below.
function isRoundVisible(division, round) {
  return !!division && Array.isArray(division.visibleRounds) && division.visibleRounds.includes(round);
}

function hydrateDivision(db, division) {
  // Filtered once here, then reused below - computeStandings/
  // computeTeamStandings used to each be handed the *whole* db.fixtures
  // array and re-filter it by divisionId themselves, meaning every call to
  // hydrateDivision (every division page load, every roster/fixture change)
  // did two full scans over every fixture in the entire app instead of one.
  const fixtures = db.fixtures.filter((f) => f.divisionId === division.id);
  const league = db.leagues.find((l) => l.id === division.leagueId);
  const leagueName = league ? league.name : null;

  if (division.entryType === 'teams') {
    const teams = db.teams
      .filter((t) => division.teamIds.includes(t.id))
      .map((t) => ({ ...t, players: db.players.filter((p) => t.playerIds.includes(p.id)) }));
    const standings = computeTeamStandings(division, fixtures, db.teams);
    return { ...division, leagueName, teams, fixtures, standings };
  }

  if (division.entryType === 'doubles') {
    const pairings = db.pairings
      .filter((p) => division.pairingIds.includes(p.id))
      .map((p) => ({ ...p, players: db.players.filter((pl) => p.playerIds.includes(pl.id)) }));
    // computeStandings just needs an entrant-id list (division.playerIds) and
    // a matching list of { id, name } entrants to label rows with - a Pairing
    // already has both fields, so this reuses the singles standings
    // calculation unmodified rather than needing its own version.
    const standings = computeStandings({ ...division, playerIds: division.pairingIds }, fixtures, pairings);
    return { ...division, leagueName, pairings, fixtures, standings };
  }

  const players = db.players.filter((p) => division.playerIds.includes(p.id));
  const standings = computeStandings(division, fixtures, db.players);
  return { ...division, leagueName, players, fixtures, standings };
}

app.get('/api/divisions/:id', requireAuth, asyncRoute((req, res) => {
  const db = readDb();
  const division = db.divisions.find((d) => d.id === req.params.id);
  if (!division) throw new ApiError(404, 'Division not found');
  const hydrated = hydrateDivision(db, division);
  // A non-admin only ever sees fixtures from rounds the admin has released -
  // see isRoundVisible above. Standings are left untouched (computed from the
  // full fixture list before this filter) since a not-yet-released round
  // shouldn't have any results on it under normal use anyway.
  if (!req.auth.user.isAdmin) {
    hydrated.fixtures = hydrated.fixtures.filter((f) => isRoundVisible(division, f.round));
  }
  res.json(hydrated);
}));

// ---- Singles players ----
// Players are only ever registered `Users` now (see registeredPlayers()
// below) - a captain picks a name from the list of people who've actually
// signed up rather than typing an arbitrary free-text name. This keeps the
// roster tied to real accounts instead of one-off placeholder names.

// Every registered, active user has (via registration) a linked Player
// record - this is the pool of names a captain/admin can pick from when
// building a division roster or a team. Demo/seed players created directly
// in db.players without a linked user (e.g. the seeded Premier League demo
// data) are NOT included here, since they don't correspond to a real account.
function registeredPlayers(db) {
  const linkedPlayerIds = new Set(
    db.users.filter((u) => u.status === 'active' && u.playerId).map((u) => u.playerId)
  );
  return db.players
    .filter((p) => linkedPlayerIds.has(p.id))
    .sort((a, b) => a.name.localeCompare(b.name));
}

app.get('/api/registered-players', requireAuth, asyncRoute((req, res) => {
  const db = readDb();
  res.json(registeredPlayers(db));
}));

// Powers the admin "Game Adjustments" page (search a player, then pick the
// fixture to adjust) - same shape/logic as GET /api/users/me/fixtures, just
// parameterized to any playerId rather than the logged-in account's own, and
// admin-only. Includes every status (not just upcoming) since an admin might
// specifically be looking for a `disputed` or `pending_confirmation` match to
// resolve.
app.get('/api/admin/players/:playerId/fixtures', requireAdmin, asyncRoute((req, res) => {
  const db = readDb();
  const playerId = req.params.playerId;
  const myTeamIds = db.teams.filter((t) => t.playerIds.includes(playerId)).map((t) => t.id);
  const myPairingIds = db.pairings.filter((p) => p.playerIds.includes(playerId)).map((p) => p.id);

  const fixtures = db.fixtures.filter((f) => {
    if (f.homePlayerId === playerId || f.awayPlayerId === playerId) return true;
    if (myTeamIds.includes(f.homeTeamId) || myTeamIds.includes(f.awayTeamId)) return true;
    if (myPairingIds.includes(f.homePlayerId) || myPairingIds.includes(f.awayPlayerId)) return true;
    if (f.legs) return f.legs.some((l) => l.homePlayerId === playerId || l.awayPlayerId === playerId);
    return false;
  });

  const enriched = fixtures.map((f) => {
    const division = db.divisions.find((d) => d.id === f.divisionId);
    const league = db.leagues.find((l) => l.id === f.leagueId);
    const isTeams = !!f.legs;
    const isDoubles = division?.entryType === 'doubles';
    const opponentId = isTeams
      ? (myTeamIds.includes(f.homeTeamId) ? f.awayTeamId : f.homeTeamId)
      : isDoubles
        ? (myPairingIds.includes(f.homePlayerId) ? f.awayPlayerId : f.homePlayerId)
        : (f.homePlayerId === playerId ? f.awayPlayerId : f.homePlayerId);
    const opponentName = isTeams
      ? db.teams.find((t) => t.id === opponentId)?.name
      : isDoubles
        ? db.pairings.find((p) => p.id === opponentId)?.name
        : db.players.find((p) => p.id === opponentId)?.name;
    return {
      id: f.id,
      leagueName: league?.name,
      divisionName: division?.name,
      round: f.round,
      status: f.status,
      scoreLabel: isTeams ? `${f.homeLegsWon}-${f.awayLegsWon} legs` : `${f.homeFrameScore}-${f.awayFrameScore} frames`,
      scheduledDate: f.scheduledDate || null,
      opponentName: opponentName || 'TBD',
    };
  });

  enriched.sort((a, b) => (b.scheduledDate || '').localeCompare(a.scheduledDate || '') || b.round - a.round);
  res.json(enriched);
}));

// Powers the Game Adjustments page's "Needs Attention" list - every
// pending_confirmation/disputed result across the whole app, so an admin can
// jump straight to resolving one without first knowing (and searching for)
// which player it involves. Scans both fixture-level status (singles/
// doubles) and leg-level status (team fixtures, since an individual leg can
// be disputed while the overall team match is still in_progress).
app.get('/api/admin/fixtures/needs-attention', requireAdmin, asyncRoute((req, res) => {
  const db = readDb();
  const NEEDS_ATTENTION = ['pending_confirmation', 'disputed'];
  const results = [];

  for (const f of db.fixtures) {
    const division = db.divisions.find((d) => d.id === f.divisionId);
    const league = db.leagues.find((l) => l.id === f.leagueId);

    if (f.legs) {
      const homeTeam = db.teams.find((t) => t.id === f.homeTeamId);
      const awayTeam = db.teams.find((t) => t.id === f.awayTeamId);
      for (const leg of f.legs) {
        if (!NEEDS_ATTENTION.includes(leg.status)) continue;
        results.push({
          fixtureId: f.id,
          legNumber: leg.legNumber,
          leagueName: league?.name,
          divisionName: division?.name,
          round: f.round,
          status: leg.status,
          label: `${homeTeam ? homeTeam.name : 'TBD'} vs ${awayTeam ? awayTeam.name : 'TBD'} — Leg ${leg.legNumber}`,
          scoreLabel: `${leg.homeFrameScore}-${leg.awayFrameScore} frames`,
          disputeReason: leg.disputeReason || null,
          noShowClaim: leg.noShowClaim || null,
        });
      }
      continue;
    }

    if (!NEEDS_ATTENTION.includes(f.status)) continue;
    const isDoubles = division?.entryType === 'doubles';
    const homeName = isDoubles
      ? db.pairings.find((p) => p.id === f.homePlayerId)?.name
      : db.players.find((p) => p.id === f.homePlayerId)?.name;
    const awayName = isDoubles
      ? db.pairings.find((p) => p.id === f.awayPlayerId)?.name
      : db.players.find((p) => p.id === f.awayPlayerId)?.name;
    results.push({
      fixtureId: f.id,
      legNumber: null,
      leagueName: league?.name,
      divisionName: division?.name,
      round: f.round,
      status: f.status,
      label: `${homeName || 'TBD'} vs ${awayName || 'TBD'}`,
      scoreLabel: `${f.homeFrameScore}-${f.awayFrameScore} frames`,
      disputeReason: f.disputeReason || null,
      noShowClaim: f.noShowClaim || null,
    });
  }

  const STATUS_ORDER = { disputed: 0, pending_confirmation: 1 };
  results.sort((a, b) =>
    STATUS_ORDER[a.status] - STATUS_ORDER[b.status] ||
    (a.leagueName || '').localeCompare(b.leagueName || '') ||
    a.round - b.round
  );
  res.json(results);
}));
